import type { Metadata } from 'next';
import Header from '@/components/Header';
import { Lato } from "next/font/google";
import './globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  icons: {
    icon: '/images/parking-time-logo.png',
  },
};

const lato = Lato({ subsets: ["latin"],  weight: "400"
 });


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en"
    style={{ scrollBehavior: 'smooth' }}>
      <body className={lato.className}>
        <Header />
        {children}
      </body>
    </html>
  );
}
