import {NextIntlClientProvider} from 'next-intl';
import {getMessages} from 'next-intl/server';
import type { Metadata } from 'next';
import Header from '@/components/Header';
import { Lato } from 'next/font/google';
import "../../../src/app/globals.css";
import Footer from '@/components/Footer';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  icons: {
    icon: '/images/parking-time-logo.png',
  },
};

const lato = Lato({ subsets: ['latin'], weight: '400' });

export default async function RootLayout({
  children,
  params: {locale}
}: {
  children: React.ReactNode;
  params: {locale: string};
}) {
  // Providing all messages to the client
  // side is the easiest way to get started
  const messages = await getMessages();
 
  return (
    <html lang={locale} style={{ scrollBehavior: 'smooth' }} suppressHydrationWarning={true}>
      <body className={lato.className}>
        <NextIntlClientProvider messages={messages}>
        <Header />
          {children}
        <Footer />  
        </NextIntlClientProvider>
      </body>
    </html>
  );
}







